# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb80d855730c344e3e707c64525167b046036278fce225dbd6a88b7fdb9ffc07cfd91dc967742da5674b8c2888ef7db64987789a70793e7c0955140adc0a70ef

test:
  secret_key_base: abde18c9bd3adcedf50f6e39017e4755c3fca0febede472394681aa81827964ac21b191b8e47860f78d42b24317dc895ba473941d5e76d10e1044f3b65d5990a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
